version: '3'

services:
  web:
    build: .
    command: >
      sh -c "python /app/manage.py migrate &&
             python /app/manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8083:8000"
    environment:
      DEBUG: "False"
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: poc_demo
      POSTGRES_HOST: my-postgres

networks:
  default:
    external:
      name: my-bridge